import { Schema } from "effect";

/**
 * Shared validation constants
 */
export const TASK_MAX_LENGTH = 50000;

/**
 * Valid run status values
 * - started: Task accepted, sandbox spinning up
 * - running: OpenCode is actively working
 * - completed: Finished successfully
 * - failed: Finished with error
 */
export const RunStatus = Schema.Literal(
	"started",
	"running",
	"completed",
	"failed",
);
export type RunStatus = typeof RunStatus.Type;

/**
 * Result of a completed run - simplified to unstructured output
 */
export const RunResult = Schema.Struct({
	success: Schema.Boolean,
	output: Schema.String,
	error: Schema.optionalWith(Schema.String, { exact: true }),
});
export type RunResult = typeof RunResult.Type;

/**
 * Complete run record stored in R2
 */
export const RunRecord = Schema.Struct({
	runId: Schema.String,
	sessionId: Schema.String,
	workflowId: Schema.String,
	status: RunStatus,
	task: Schema.String,
	title: Schema.String, // Short label (provided or auto-generated by OpenCode)
	model: Schema.String,
	startedAt: Schema.Number,
	completedAt: Schema.optionalWith(Schema.Number, { exact: true }),
	result: Schema.optionalWith(RunResult, { exact: true }),
});
export type RunRecord = typeof RunRecord.Type;
